const lang = {
    ru: {
        prepareView: [
            'Комплексный экзамен',
            'Экзамен',
            'Предмет',
            'Время',
            'мин.',
            'неограничено', 
            'Билет',
            'Выберите язык',
            'Начать',
            'Экзамен начнётся через',
        ],
        authView: [
            'Введите данные для входа',
            'Кто входит в систему?',
            'Укажите из списка',
            'Форма обучения',
            'Выберите форму обучения',
            'Курс',
            'Укажите свой курс',
            'Группа',
            'Укажите свою группу',
            'Отдел',
            'Кафедра',
            'Укажите свой отдел',
            'Укажите свою кафедру',
            'Ф.И.О.',
            'Выберите себя из списка',
            'Список пуст', // 15
            'Пароль',
            'Введите пароль',
            'Назад',
            'Войти',
            'Успешная авторизация',
            'Неверный пароль пользователя', // 21
            'Временные неполадки на стороне Auth-сервера',
            'Обучающийся',
            'Абитуриент',
            'Преподаватель',
            'Сотрудник',
            'Очная форма обучения',
            'Заочная форма обучения',
            'Магистратура'
        ],
        coordinatorView: [
            'У вас нет активных экзаменов',
            'Экзамен',
            'Комплексный экзамен',
            'Автоматическое сохранение незаконченного экзамена',
            'Предмет',
            'Время',
            'Вопросов',
            'Начало',
            'Предметы',
            'Старт',
            'по команде админа',
            'Подробнее об экзамене',
            'Информация об экзамене',
            'Информация об комплексном экзамене',
            'Время начала',
            'Время окончания',
            'Название предмета',
            'Кол-во билетов',
            'Кол-во вопросов',
            'Отведённое время',
            'Темы',
            'Время на 1 вопрос',
            'Доступные языки',
            'Возможность изменить ответ',
            'Система оценки',
            'отлично',
            'хорошо',
            'удовлетворительно',
            'неограничено',
            'мин.', // 29
            'Начать экзамен',
            'и др.',
            'Экзамен завершён',
            'Экзамен ещё не начат',
            'Данный пользователь этот проходит экзамен'
        ],
        initView: [
            'Проверка зависимостей',
            'Подключение к серверам',
            'Проверка сокета клиента',
            'Запуск клиента',
            'Сменить IP-адреса',
            'Не удаётся подключиться к управляющему серверу. Как только подключение будет восстановлено, программа запуститься. Так же вы можете сменить IP-адреса серверов',
            'Не удаётся подключиться к раздающему серверу. Как только подключение будет восстановлено, программа запуститься. Так же вы можете сменить IP-адреса серверов',
            'Не удаётся подключиться к серверу аутентификации. Как только подключение будет восстановлено, программа запуститься. Так же вы можете сменить IP-адреса серверов',
            'Не удаётся подключиться к управляющему серверу для проверки клиента. Как только подключение будет восстановлено, программа запуститься. Так же вы можете сменить IP-адреса серверов'
        ],
        examView: [
            'экзамен остановлен администратором',
            'время сдачи экзамена вышло',
            'Отправка ответов на проверку..',
            'Билет',
            'Тема вопроса',
            'Сложность',
            'Лёгкий',
            'Средний',
            'Трудный',
            'Время вопроса',
            'Вопросы',
            'Время',
            'не ограничено',
            'Предмет',
            'Отправить',
            'Ваш результат',
            'Оценка',
            'Процентное соотношение',
            'Вопросы',
            'верные ответы',
            'неверные ответы',
            'Количество правильных ответов',
            'Количество неверных ответов',
            'Обучающийся',
            'Абитуриент',
            'Преподаватель', // 25
            'Сотрудник',
            'Форма обучения',
            'Курс',
            'Группа',
            'Кафедра',
            'Отдел',
            'Отправка ответов на проверку',
            'Выйти',
            'очная',
            'заочная',
            'магистратура',
            'Вопросы',
            'Контекст ?-ов',
            'простой вопрос',
            'вопрос с изображениями',
            'вопрос с выбираемой областью',
            'отвечено',
            'Экзаменируемый', // 43
            'Балл',
            'набранный вами балл',
            'макс. балл по билету',
        ]
    },
    uz_l: {
        prepareView: [
            "Kompleks imtihon",
            "Imtihon",
            'Fan',
            "Vaqt",
            'min.',
            "cheklanmagan",
            "Chipta",
            "Tilni tanlang",
            'Boshlash',
            "Imtihon boshlanadi",
        ],
        authView: [
            "Kirish ma'lumotlaringizni kiriting",
            "Kim tizimga kirmoqda?",
            "Ro'yxatdan belgilang",
            "Ta'lim shakli",
            "Ta'lim shaklini tanlang",
            "Kurs",
            "Kursingizni belgilang",
            "Guruh",
            "Guruhingizni belgilang",
            "Bo'lim",
            'Kafedra',
            "Bo'limingizni belgilang",
            "Kafedrengizni belgilang",
            'F.I.Sh.',
            "Ro'yxatdan o'zingizni tanlang",
            "Ro'yxat bo'sh",
            "Parol",
            "Parolni kiriting",
            "Orqaga",
            'Kirish',
            "Muvaffaqiyatli avtorizatsiya",
            "Foydalanuvchi paroli noto'g'ri",
            "Auth-server tomonida vaqtinchalik muammolar",
            "Talaba",
            "Abituriyent",
            "O'qituvchi",
            "Xodim",
            "Kunduzgi ta'lim",
            "Sirtqi ta'lim",
            'Magistratura'
        ],
        coordinatorView: [
            "Sizda faol imtihonlar yo'q",
            "imtihon",
            "Kompleks imtihon",
            "Tugallanmagan imtihonlarni avtomatik saqlash",
            'Fan',
            "Vaqt",
            "Savollar",
            "Boshlanish",
            "Fanlar",
            "Boshlanish",
            "administrator tomonidan",
            "Imtihon haqida batafsil",
            "imtihon haqida ma'lumot",
            "Kompleks imtihon haqida ma'lumot",
            'Boshlanish vaqti',
            "Yakuniy vaqt",
            "Fan nomi",
            "Chiptalar soni",
            "Savollar soni",
            "Ajratilgan vaqt",
            "Mavzular",
            "1 savol uchun vaqt",
            "Mavjud tillar",
            "Javobni o'zgartirish imkoniyati",
            "Baholash tizimi",
            "ajoyib",
            "yaxshi",
            "qoniqarli",
            "cheklanmagan",
            'daq.',
            "Imtihonni boshlash",
            'va boshq.',
            "Imtihon yakunlandi",
            "Imtihon hali boshlanmagan",
            "Ushbu foydalanuvchi imtihon topshirmoqda"
        ],
        initView: [
            "Bog'liklarni tekshirish",
            "Serverlarga ulanish",
            "Mijoz soketini tekshirish",
            "Mijozni ishga tushirish",
            "IP manzillarni o'zgartirish",
            "Boshqaruv serveriga ulanib bo'lmadi. Ulanish tiklanishi bilan dastur ishga tushadi. Shuningdek, siz serverlarning IP manzillarini o'zgartirishingiz mumkin",
            "Distribyutor serveriga ulanib bo'lmadi. Ulanish tiklanishi bilan dastur ishga tushadi. Shuningdek, siz serverlarning IP manzillarini o'zgartirishingiz mumkin",
            "Autentifikatsiya serveriga ulanib bo'lmadi. Ulanish tiklanishi bilan dastur ishga tushadi. Shuningdek, siz serverlarning IP manzillarini o'zgartirishingiz mumkin",
            "Mijozni tekshirish uchun boshqaruv serveriga ulanib bo'lmadi. Ulanish tiklanishi bilan dastur ishga tushadi. Shuningdek, siz serverlarning IP manzillarini o'zgartirishingiz mumkin"
        ],
        examView: [
            "imtihon administrator tomonidan to'xtatildi",
            "imtihon vaqti tugadi",
            "Javoblar ko'rib chiqish uchun yuborilmoqda...",
            "chipta",
            "Savol mavzusi",
            "Murakkablik",
            "Oson",
            "O'rtacha",
            "Qiyin",
            "Savol vaqti",
            "Savollar",
            "Vaqt",
            "cheklanmagan",
            'Fan',
            "Yuborish",
            "Sizning natijangiz",
            "Baho",
            "foiz",
            "Savollar",
            "to'g'ri javoblar",
            "noto'g'ri javoblar",
            "To'g'ri javoblar soni",
            "Noto'g'ri javoblar soni",
            "Talaba",
            "Abiturient",
            "O'qituvchi",
            "Xodim",
            "Ta'lim shakli",
            "Kurs",
            "Guruh",
            'Kafedra',
            "Bo'lim",
            "Javoblarni ko'rib chiqish uchun yuborish",
            'Chiqish',
            "kunduzgi ta'lim",
            "sirtqi ta'lim",
            'magistratura',
            "Savollar",
            'Kontekst',
            "oddiy savol",
            "rasmlar bilan savol",
            'tanlanadigan maydon bilan savol',
            'javob berildi',
            "Imtihon oluvchi", // 44
            'Ball',
            'siz toplagan ball',
            'maks. chiptadagi ball',
        ]
    }
}

export default lang